version: '3.8'

services:
  flask:
    build: ./backend
    ports:
      - "5009:5009"
    volumes:
      - ./backend:/app

  react:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - flask
